global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'litellm'
    static_configs:
      - targets: ['litellm:4000','exposable-prestatistical-autumn.ngrok-free.dev']  # Assuming Litellm exposes metrics at port 4000
